function createfigure(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 06-Nov-2012 11:30:19

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YDir','reverse',...
    'XTickLabel',{'link 0','link 1','2','3','4'},...
    'XTick',[-0.5 0.5 1.5 2.5 3.5],...
    'Layer','top');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.5 4.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.5 6.5]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image([0 1 2 3 4],[0 1 2 3 4 5 6],cdata1,'Parent',axes1,...
    'CDataMapping','scaled');

% Create xlabel
xlabel('Downstream');

% Create ylabel
ylabel('Densities');

% Create colorbar
colorbar('peer',axes1);

