!git checkout master;
clear all;
plotForwardSim('networks/samitha1onramp.json');
!git checkout dhdx;
clear all;
loadParameters;
scen = loadScenario('networks/samitha1onramp.json');
T = scen.T; N = scen.N;
u = ones(T,N);
plotForwardSim(scen,u);