function out = rampOptimalUGradientDescent(scen, u)
clear rampStore;
global rampStore;
global parameters;

rampStore.scen = scen;
rampStore.u = u;

out = unstack(...
  gradientDescent(stacker(u),...
  @rampCostFunctionFromControl,...
  @rampGradientFromControl,...
  parameters.globalMaxIterations, ...
  parameters.lineSearch,...
  @stopIterating),...
  scen);
end